microservice-chart:
  namespace: "idpay"
  nameOverride: ""
  fullnameOverride: ""

  livenessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 15
    periodSeconds: 10

  readinessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 125
    failureThreshold: 15
    periodSeconds: 10

  deployment:
    create: true

  service:
    create: true
    type: ClusterIP
    ports:
      - 8080

  ingress:
    create: true
    path: /idpaytransactions/(.*)
    servicePort: 8080

  serviceAccount:
    create: false
    annotations: { }
    name: ""

  podAnnotations: { }

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 10000
    runAsGroup: 10000

  envConfig:
    MONGODB_DBNAME: "idpay"
    APPLICATIONINSIGHTS_ROLE_NAME: "idpaytransactions"
    APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
    APPLICATIONINSIGHTS_INSTRUMENTATION_MICROMETER_ENABLED: "false"
    APPLICATIONINSIGHTS_PREVIEW_PROFILER_ENABLED: "false"
    KAFKA_NOTIFICATION_GROUP_ID: "idpay-commands-transactions-consumer-group"
    DELETE_PAGINATION_SIZE: "45"
    DELETE_DELAY_TIME: "1000"

  externalConfigMapValues:
    idpay-common:
      TZ: TZ
    idpay-eventhub-01:
      KAFKA_BINDER_BROKER_ENDPOINT_REWARD_TRX: kafka_broker
      KAFKA_TRANSACTIONS_SASL_MECHANISM: kafka_sasl_mechanism
      KAFKA_TRANSACTIONS_SECURITY_PROTOCOL: kafka_security_protocol
      KAFKA_TRANSACTION_TOPIC: idpay_transaction_topic
      KAFKA_TRANSACTION_GROUP_ID: idpay_transaction_consumer_group
      KAFKA_ERRORS_BROKER: kafka_broker
      KAFKA_ERRORS_TOPIC: idpay_error_topic
      KAFKA_COMMANDS_BROKER: kafka_broker
      KAFKA_COMMANDS_TOPIC: idpay_commands_topic

  envSecret:
    MONGODB_URI: mongodb-connection-string
    EVH_CONNECTION_REWARD_RESPONSE: evh-idpay-transaction-idpay-transaction-consumer-jaas-config-idpay-01
    KAFKA_ERRORS_SASL_JAAS_CONFIG: evh-idpay-errors-idpay-errors-producer-jaas-config-idpay-01
    KAFKA_COMMANDS_SASL_JAAS_CONFIG: evh-idpay-commands-idpay-commands-consumer-jaas-config-idpay-01
    PDV_DECRYPT_API_KEY: pdv-api-key

  externalConfigMapFiles:
    create: true
    configMaps:
      - name: appinsights-config
        key: applicationinsights.json